### PR TITLE
Implement Create GUI Config Editor

### LINKED ISSUE #12: Create GUI Config Editor
Add an option (File > Edit config) to open a new window to edit the ~/mmpConfig.yml file. 

- Edit macro pad layout (2x2, 3x3, etc.)
  - ```
    [ 1 ] [ 2 ]
    [ 3 ] [ 4 ]
    ```
- Click on one of the buttons from the layout view to edit the Actions for that button. Display the relevant list of actions for the button. (Also have a "+ Add")
  - ```
    Actions for button [ 1 ]:
    - [PressRelease | 'enter']
    - [SendString | 'gg']
    - [PressRelease | 'enter']
    ```
  - Clicking on the Action name will open a dropdown showing list of available options. 
    - On new selection, clear the value
  - Clicking on the value will set the value. (Either type it, or show dropdown, or ...)
- Save changes button, also save as

### PR DESCRIPTION
**Pull request by ssebs**
Resolve #12 and #20

### CODE REVIEW

**Comment by andydotxyz** [comment]
You could avoid the GTK dependency by using the Fyne dialogs package :).

**Comment by ssebs** [comment]
I was originally using the fyne dialog, but it was hard to navigate and I wanted an OS native one.

Thanks for the suggestion!

**Comment by andydotxyz** [comment]
> but it was hard to navigate and I wanted an OS native one.

Please be aware that GTK is not necessarily native - there are 3 or more toolkits for Linux and users will have their own preference. We created the one inside Fyne so that we knew it would work everywhere.
I understand your workaround but you're asking KDE or Enlightenment users to install a whole new toolkit to support that dialog choice.

**Comment by ssebs** [comment]
Oh wow I didn't realize you were the main contributor of fyne 😅.

I chose this library following this comment: https://github.com/fyne-io/fyne/issues/458#issuecomment-533898622

I would love to have a native-ish looking dialog, but since this project is primarily for windows users I thought the workaround was OK for now.

**Comment by ssebs** [comment]
Also doing #20 while I'm at it

**Comment by ssebs** [comment]
Before:

https://github.com/user-attachments/assets/10a220b7-b671-441f-8091-367c88647971

After:

https://github.com/user-attachments/assets/93dba44d-0294-4836-9b47-f18b098d896a

**Pull request merged**
